version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: taskManagerDataBaseg
    restart: always
    environment:
      POSTGRES_DB: taskManDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahsas125
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  esdata: